name: Run Code Recup Script Nightly

on:
  workflow_dispatch:  # Permet un déclenchement manuel
  schedule:
    - cron: '30 22 * * 2-5'  # Exécution à 22h30 UTC (23h30 heure française)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Récupérer les fichiers du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Configurer Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Version Python (adaptez selon vos besoins)

      # Étape 3 : Installer les dépendances (si nécessaire)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || echo "Pas de dépendances à installer"

      # Étape 4 : Exécuter le script
      - name: Run Code Recup Script
        run: python code_recup/code_recup.py  # Chemin vers le fichier
